# Spring properties
spring:
  application:
    name: github-mining  # Service registers under this name
  freemarker:
    enabled: true           # Ignore Eureka dashboard FreeMarker templates

  datasource:
    driver-class-name: org.h2.Driver # In-memory DB
    url: jdbc:h2:mem:gitHubMiningDb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hibernate:
          hbm2ddl:
            auto: create
          format_sql: true
    show-sql: false

# HTTP Server
server.port: 8080   # HTTP (Tomcat) port
